<#
D-Drive Windows installer (PowerShell)
Cross-platform alternative to install.sh for Windows users.
Usage:
  - From repository: Open PowerShell and run: .\install.ps1
  - Remote (one-liner): iwr -useb https://raw.githubusercontent.com/jasonzli-DEV/D-Drive/main/install.ps1 | iex
#>
[CmdletBinding()]
param(
    [string]$RepoUrl = 'https://github.com/jasonzli-DEV/D-Drive.git',
    [string]$InstallDir = "$env:USERPROFILE\d-drive",
    [switch]$Force
)

Set-StrictMode -Version Latest

function Write-Info { Write-Host "[INFO]" -ForegroundColor Green; Write-Host $args }
function Write-Warn { Write-Host "[WARN]" -ForegroundColor Yellow; Write-Host $args }
function Write-Err  { Write-Host "[ERROR]" -ForegroundColor Red; Write-Host $args }

function Test-Command($name) {
    return (Get-Command $name -ErrorAction SilentlyContinue) -ne $null
}

function New-Hex([int]$bytes){
    $b = New-Object byte[] $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    ($b | ForEach-Object { $_.ToString('x2') }) -join ''
}

# Checks
Write-Info "Checking for Git..."
if (-not (Test-Command git)) { Write-Err "git is required but not found in PATH."; exit 1 }

Write-Info "Checking for Docker..."
if (-not (Test-Command docker)) {
    Write-Warn "Docker is not installed or not in PATH. Attempting automatic install where possible..."

    # Try winget first (Windows 10/11)
    if (Test-Command winget) {
        Write-Info "Installing Docker Desktop via winget (may require elevation)..."
        try { winget install --id Docker.DockerDesktop -e --accept-package-agreements --accept-source-agreements } catch { Write-Warn "winget install failed or requires manual approval." }
    }

    # Fallback to Chocolatey if available
    if (-not (Test-Command docker) -and (Test-Command choco)) {
        Write-Info "Installing Docker Desktop via Chocolatey..."
        try { choco install docker-desktop -y } catch { Write-Warn "choco install failed." }
    }

    # Allow time for installer to finish and PATH to refresh
    $installed = $false
    for ($i=0; $i -lt 60; $i++) {
        if (Test-Command docker) { Write-Info "Docker installed: $(docker --version)"; $installed = $true; break }
        Start-Sleep -Seconds 2
    }

    if (-not $installed) {
        Write-Err "Automatic Docker installation did not succeed. Please install Docker Desktop manually from https://docs.docker.com/desktop/windows/."
        exit 1
    }
} else {
    docker --version | Write-Host
}

# Ensure Docker daemon is running
try {
    docker info *> $null
} catch {
    Write-Warn "Docker daemon is not running or not accessible. Attempting to start Docker Desktop..."
    try { Start-Process 'Docker Desktop' -ErrorAction SilentlyContinue } catch { }

    $ready = $false
    for ($i=0; $i -lt 60; $i++) {
        try { docker info *> $null; $ready = $true; break } catch { Start-Sleep -Seconds 2 }
    }
    if (-not $ready) { Write-Err "Docker daemon did not become available. Please start Docker Desktop or the Docker service."; exit 1 }
}

Write-Info "Checking for Docker Compose..."
$composeMode = $null
try {
    docker compose version *> $null
    $composeMode = 'v2'
} catch {
    # v2 not available
}
if (-not $composeMode) {
    if (Test-Command docker-compose) { $composeMode = 'v1' } else { Write-Err "Docker Compose not found."; exit 1 }
}
$composeLabel = if ($composeMode -eq 'v2') { 'docker compose (v2)' } else { 'docker-compose (v1)' }
Write-Info "Using: $composeLabel"

function Invoke-Compose {
    param(
        [Parameter(ValueFromRemainingArguments=$true)]
        [string[]]$Args
    )
    if ($composeMode -eq 'v2') {
        & docker compose @Args
    } else {
        & docker-compose @Args
    }
}

# Clone or update repo
if (Test-Path $InstallDir) {
    Write-Info "D-Drive directory exists, attempting to update..."
    Push-Location $InstallDir
    try { git pull origin main } catch { Write-Warn "git pull failed, continuing" }
    Pop-Location
} else {
    Write-Info "Cloning D-Drive into $InstallDir..."
    git clone $RepoUrl $InstallDir
}

Set-Location $InstallDir

# Generate secrets
$envFile = Join-Path $InstallDir '.env'
if ((Test-Path $envFile) -and (-not $Force)) {
    Write-Warn ".env already exists. Use -Force to overwrite. Skipping secret generation."
} else {
    Write-Info "Generating secure secrets..."
    $JWT_SECRET = New-Hex 32
    $POSTGRES_PASSWORD = New-Hex 16

    $content = @"
# Auto-generated by D-Drive installer (Windows)
# Discord configuration will be set via the web setup wizard

# Database
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# JWT Secret
JWT_SECRET=$JWT_SECRET

# URLs (adjust if running on different host/port)
FRONTEND_URL=http://localhost
# Use /api for Docker deployment (nginx proxies to backend)
VITE_API_URL=/api

# Discord Configuration (set via web setup wizard)
# DISCORD_CLIENT_ID=
# DISCORD_CLIENT_SECRET=
# DISCORD_BOT_TOKEN=
# DISCORD_GUILD_ID=
# DISCORD_CHANNEL_ID=
"@

    $content | Out-File -FilePath $envFile -Encoding utf8 -Force

    # Restrict file ACL to current user
    try {
        $user = "$env:USERDOMAIN\$env:USERNAME"
        $acl = Get-Acl $envFile
        $acl.SetAccessRuleProtection($true, $false)
        $acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) }
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule($user, 'FullControl', 'ContainerInherit,ObjectInherit', 'None', 'Allow')
        $acl.AddAccessRule($rule)
        Set-Acl -Path $envFile -AclObject $acl
        Write-Info "Created .env and restricted file permissions to current user."
    } catch {
        Write-Warn "Failed to set strict ACL on .env; please secure it manually."
    }
}

# Start services
Write-Info "Building and starting D-Drive services..."
Invoke-Compose build 2>$null

Write-Info "Starting all services..."
$null = Start-Job -ScriptBlock { 
    param($dir, $mode)
    Set-Location $dir
    if ($mode -eq 'v2') {
        & docker compose up -d
    } else {
        & docker-compose up -d
    }
} -ArgumentList $InstallDir, $composeMode | Wait-Job | Receive-Job

# Wait for services to be healthy
Write-Info "Waiting for services to be ready..."
Start-Sleep -Seconds 5

$maxAttempts = 30
for ($i = 0; $i -lt $maxAttempts; $i++) {
    try {
        $psOutput = Invoke-Compose ps --format json 2>$null
        if ($psOutput) {
            $containers = $psOutput | ConvertFrom-Json
            $healthyCount = ($containers | Where-Object { 
                $_.Health -eq 'healthy' -or ($_.State -eq 'running' -and -not $_.Health) 
            }).Count
            
            if ($healthyCount -ge 3) {
                break
            }
        }
    } catch { }
    Start-Sleep -Seconds 2
}

Write-Info "Services started. Current status:"
Invoke-Compose ps | Write-Host

$composeCmd = if ($composeMode -eq 'v2') { 'docker compose' } else { 'docker-compose' }
Write-Host "`n✅ Installation complete! D-Drive is running at http://localhost" -ForegroundColor Green
Write-Host "   Complete the setup wizard to configure Discord OAuth" -ForegroundColor Cyan
Write-Host "`nTo view logs: $composeCmd logs -f" -ForegroundColor Gray
