#!/bin/bash
set -e

# D-Drive Installation Script
# This script installs D-Drive with a single command

REPO_URL="https://github.com/jasonzli-DEV/D-Drive.git"
INSTALL_DIR="${DDRIVE_INSTALL_DIR:-$HOME/d-drive}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_banner() {
    echo -e "${BLUE}"
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║                                                               ║"
    echo "║     ██████╗       ██████╗ ██████╗ ██╗██╗   ██╗███████╗       ║"
    echo "║     ██╔══██╗      ██╔══██╗██╔══██╗██║██║   ██║██╔════╝       ║"
    echo "║     ██║  ██║█████╗██║  ██║██████╔╝██║██║   ██║█████╗         ║"
    echo "║     ██║  ██║╚════╝██║  ██║██╔══██╗██║╚██╗ ██╔╝██╔══╝         ║"
    echo "║     ██████╔╝      ██████╔╝██║  ██║██║ ╚████╔╝ ███████╗       ║"
    echo "║     ╚═════╝       ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝  ╚══════╝       ║"
    echo "║                                                               ║"
    echo "║           Discord-Based Cloud Storage System                  ║"
    echo "║                                                               ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_docker() {
    log_info "Checking for Docker..."
    
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed."
        echo ""
        echo "Please install Docker first:"
        echo "  - macOS: https://docs.docker.com/desktop/install/mac-install/"
        echo "  - Windows: https://docs.docker.com/desktop/install/windows-install/"
        echo "  - Linux: https://docs.docker.com/engine/install/"
        echo ""
        echo "Or run: curl -fsSL https://get.docker.com | sh"
        exit 1
    fi
    
    log_info "Docker found: $(docker --version)"
}

check_docker_compose() {
    log_info "Checking for Docker Compose..."
    
    # Check for docker compose (v2) or docker-compose (v1)
    if docker compose version &> /dev/null; then
        COMPOSE_CMD="docker compose"
        log_info "Docker Compose found: $(docker compose version)"
    elif command -v docker-compose &> /dev/null; then
        COMPOSE_CMD="docker-compose"
        log_info "Docker Compose found: $(docker-compose --version)"
    else
        log_error "Docker Compose is not installed."
        echo ""
        echo "Docker Compose is usually included with Docker Desktop."
        echo "If using Linux, install with: sudo apt install docker-compose-plugin"
        exit 1
    fi
}

check_docker_running() {
    log_info "Checking if Docker daemon is running..."
    
    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running."
        echo ""
        echo "Please start Docker Desktop or the Docker service."
        exit 1
    fi
    
    log_info "Docker daemon is running"
}

clone_or_update_repo() {
    if [ -d "$INSTALL_DIR" ]; then
        log_info "D-Drive directory exists, updating..."
        cd "$INSTALL_DIR"
        git pull origin main
    else
        log_info "Cloning D-Drive to $INSTALL_DIR..."
        git clone "$REPO_URL" "$INSTALL_DIR"
        cd "$INSTALL_DIR"
    fi
}

generate_secrets() {
    log_info "Generating secure secrets..."
    
    # Generate random strings for secrets
    JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)
    POSTGRES_PASSWORD=$(openssl rand -base64 24 2>/dev/null || head -c 24 /dev/urandom | base64)
    
    # Create .env file with generated secrets (Discord config will be set via UI)
    if [ ! -f .env ]; then
        cat > .env << EOF
# Auto-generated by D-Drive installer
# Discord configuration will be set via the web setup wizard

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# JWT Secret
JWT_SECRET=${JWT_SECRET}

# URLs (adjust if running on different host/port)
FRONTEND_URL=http://localhost
VITE_API_URL=http://localhost:5000

# Discord Configuration (set via web setup wizard)
# DISCORD_CLIENT_ID=
# DISCORD_CLIENT_SECRET=
# DISCORD_BOT_TOKEN=
# DISCORD_GUILD_ID=
# DISCORD_CHANNEL_ID=
EOF
        log_info "Created .env file with generated secrets"
        log_info "Discord configuration will be set via the web setup wizard"
    else
        log_warn ".env file already exists, skipping generation"
    fi
}

start_services() {
    log_info "Building and starting D-Drive services..."
    
    $COMPOSE_CMD build
    $COMPOSE_CMD up -d
    
    log_info "Waiting for services to start..."
    sleep 5
    
    # Check service health
    if $COMPOSE_CMD ps | grep -q "Up"; then
        log_info "Services started successfully!"
    else
        log_warn "Some services may still be starting..."
    fi
}

print_success() {
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                                                               ║${NC}"
    echo -e "${GREEN}║              D-Drive Installation Complete!                   ║${NC}"
    echo -e "${GREEN}║                                                               ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}Open your browser and go to:${NC}"
    echo ""
    echo -e "    ${GREEN}http://localhost${NC}"
    echo ""
    echo -e "${BLUE}Complete the setup wizard to configure Discord integration.${NC}"
    echo ""
    echo -e "${YELLOW}Useful commands:${NC}"
    echo "  cd $INSTALL_DIR"
    echo "  $COMPOSE_CMD logs -f        # View logs"
    echo "  $COMPOSE_CMD down           # Stop services"
    echo "  $COMPOSE_CMD up -d          # Start services"
    echo "  $COMPOSE_CMD pull && $COMPOSE_CMD up -d --build  # Update"
    echo ""
}

# Main installation flow
main() {
    print_banner
    
    log_info "Starting D-Drive installation..."
    echo ""
    
    check_docker
    check_docker_compose
    check_docker_running
    
    echo ""
    clone_or_update_repo
    
    echo ""
    generate_secrets
    
    echo ""
    start_services
    
    print_success
}

# Run main function
main "$@"
