<#
D-Drive Windows installer (PowerShell)
Cross-platform alternative to install.sh for Windows users.
Usage:
  - From repository: Open PowerShell and run: .\install.ps1
  - Remote (one-liner): iwr -useb https://raw.githubusercontent.com/jasonzli-DEV/D-Drive/main/install.ps1 | iex
#>
[CmdletBinding()]
param(
    [string]$RepoUrl = 'https://github.com/jasonzli-DEV/D-Drive.git',
    [string]$InstallDir = "$env:USERPROFILE\d-drive",
    [switch]$Force
)

Set-StrictMode -Version Latest

function Write-Info { Write-Host "[INFO]" -ForegroundColor Green; Write-Host $args }
function Write-Warn { Write-Host "[WARN]" -ForegroundColor Yellow; Write-Host $args }
function Write-Err  { Write-Host "[ERROR]" -ForegroundColor Red; Write-Host $args }

function Test-Command($name) {
    return (Get-Command $name -ErrorAction SilentlyContinue) -ne $null
}

function New-Hex([int]$bytes){
    $b = New-Object byte[] $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    ($b | ForEach-Object { $_.ToString('x2') }) -join ''
}

# Checks
Write-Info "Checking for Git..."
if (-not (Test-Command git)) { Write-Err "git is required but not found in PATH."; exit 1 }

Write-Info "Checking for Docker..."
if (-not (Test-Command docker)) { Write-Err "Docker is not installed or not in PATH."; exit 1 }
else {
    docker --version | Write-Host
    try { docker info *> $null } catch { Write-Err "Docker daemon is not running or not accessible. Please start Docker Desktop or the Docker service."; exit 1 }
}

Write-Info "Checking for Docker Compose..."
$composeMode = $null
try {
    docker compose version *> $null
    $composeMode = 'v2'
} catch {
    # v2 not available
}
if (-not $composeMode) {
    if (Test-Command docker-compose) { $composeMode = 'v1' } else { Write-Err "Docker Compose not found."; exit 1 }
}
Write-Info ("Using: {0}" -f (if ($composeMode -eq 'v2') { 'docker compose (v2)' } else { 'docker-compose (v1)' }))

function Invoke-Compose {
    param(
        [Parameter(ValueFromRemainingArguments=$true)]
        [string[]]$Args
    )
    if ($composeMode -eq 'v2') {
        & docker compose @Args
    } else {
        & docker-compose @Args
    }
}

# Clone or update repo
if (Test-Path $InstallDir) {
    Write-Info "D-Drive directory exists, attempting to update..."
    Push-Location $InstallDir
    try { git pull origin main } catch { Write-Warn "git pull failed, continuing" }
    Pop-Location
} else {
    Write-Info "Cloning D-Drive into $InstallDir..."
    git clone $RepoUrl $InstallDir
}

Set-Location $InstallDir

# Generate secrets
$envFile = Join-Path $InstallDir '.env'
if (Test-Path $envFile -and -not $Force) {
    Write-Warn ".env already exists. Use -Force to overwrite. Skipping secret generation."
} else {
    Write-Info "Generating secure secrets..."
    $JWT_SECRET = New-Hex 32
    $POSTGRES_PASSWORD = New-Hex 16

    $content = @"
# Auto-generated by D-Drive installer (Windows)
# Discord configuration will be set via the web setup wizard

# Database
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# JWT Secret
JWT_SECRET=$JWT_SECRET

# URLs (adjust if running on different host/port)
FRONTEND_URL=http://localhost
# Use /api for Docker deployment (nginx proxies to backend)
VITE_API_URL=/api

# Discord Configuration (set via web setup wizard)
# DISCORD_CLIENT_ID=
# DISCORD_CLIENT_SECRET=
# DISCORD_BOT_TOKEN=
# DISCORD_GUILD_ID=
# DISCORD_CHANNEL_ID=
"@

    $content | Out-File -FilePath $envFile -Encoding utf8 -Force

    # Restrict file ACL to current user
    try {
        $user = "$env:USERDOMAIN\$env:USERNAME"
        $acl = Get-Acl $envFile
        $acl.SetAccessRuleProtection($true, $false)
        $acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) }
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule($user, 'FullControl', 'ContainerInherit,ObjectInherit', 'None', 'Allow')
        $acl.AddAccessRule($rule)
        Set-Acl -Path $envFile -AclObject $acl
        Write-Info "Created .env and restricted file permissions to current user."
    } catch {
        Write-Warn "Failed to set strict ACL on .env; please secure it manually."
    }
}

# Start services
Write-Info "Building and starting D-Drive services..."
Invoke-Compose build

Write-Info "Starting postgres service..."
Invoke-Compose up -d postgres

# Wait for postgres
Write-Info "Waiting for database to be ready..."
$ready = $false
for ($i=0; $i -lt 60; $i++) {
    try {
        Invoke-Compose exec -T postgres pg_isready -U ddrive *> $null
        if ($LASTEXITCODE -eq 0) { $ready = $true; break }
    } catch { }
    Start-Sleep -Seconds 2
}
if (-not $ready) {
    Write-Warn "Postgres did not report ready within timeout. Check logs with: $composeCmd logs postgres"
}

Write-Info "Starting backend..."
Invoke-Compose up -d backend

Write-Info "Starting frontend..."
Invoke-Compose up -d frontend

Write-Info "Services started. Current status:"
Invoke-Compose ps | Write-Host

Write-Host "`nInstallation complete. Open http://localhost in your browser and complete the setup wizard." -ForegroundColor Cyan
Write-Host "To view logs: $composeCmd logs -f" -ForegroundColor Yellow
